# Generated by Django 2.2.19 on 2021-04-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Originator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(max_length=50)),
                ('sex', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('trigger', models.CharField(max_length=256)),
                ('intensity', models.PositiveSmallIntegerField()),
                ('consequence', models.CharField(max_length=256)),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_originator', to='behavior.Originator')),
            ],
        ),
    ]
