# Generated by Django 2.2.19 on 2021-04-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originator',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
