# Generated by Django 2.2.19 on 2021-04-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0003_behavior_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='additional_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='behavior',
            name='behavior',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
