# Generated by Django 2.2.19 on 2021-04-01 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('behavior', '0006_week_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='week',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='weeks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
